### ISSUE TITLE
`deny_unknown_fields` can break in 1.0.205

### ISSUE THREAD

**Issue by cpg314** [serde-rs/serde#2792]
The following (reduction of a less artificial example)
```rust
#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
enum A {
    B {
        c: String,
    },
    D {
        #[serde(flatten)]
        e: E,
    },
}
#[derive(serde::Deserialize)]
struct E {}

```
compiles fine with 1.0.204 but produces the following error in 1.0.205:
```
error[E0004]: non-exhaustive patterns: `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field::__other(_)` not covered
 --> src/main.rs:1:10
  |
1 | #[derive(serde::Deserialize)]
  |          ^^^^^^^^^^^^^^^^^^ pattern `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field::__other(_)` not covered
  |
note: `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field<'_>` defined here
 --> src/main.rs:1:10
  |
1 | #[derive(serde::Deserialize)]
  |          ^^^^^^^^^^^^^^^^^^
  |          |
  |          not covered
  = note: the matched value is of type `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field<'_>`
  = note: this error originates in the derive macro `serde::Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I have bisected the changes, and the issue appears in 32958dec3bf3886961166ec651194d6f0243a497

**Comment by Mingun** [comment]
#2567 fixes that
