### ISSUE TITLE
Fallible vector deserialization

### ISSUE THREAD

**Issue by marmeladema** [serde-rs/serde#1984]
Hello!

First of all, thank for your awesome work around serde and the rust ecosystem in general! :+1: 

I have a use case that I don't think in explicitly covered by serde, or at least I could not find the right documentation or examples for it. If I am wrong, I am very sorry in advance!

In order to build robust production systems that offer best effort approach when error occurs, I need a fallible vector deserialization. By fallible, I mean that one entry can fail to deserialize but the parsing/deserialization procedure needs to continue. I would also need some form of error handling around invalid entries.

I have a solution that only works with serde_json using `RawValue`:
```Rust
use serde::de::{Deserializer, SeqAccess, Visitor};
use serde::ser::{SerializeSeq, Serializer};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq)]
pub struct VecWithError<T> {
    values: Vec<T>,
    errors: Vec<(usize, String)>,
}

impl<T> VecWithError<T> {
    pub fn into_iter(self) -> impl Iterator<Item = T> {
        self.values.into_iter()
    }

    pub fn errors(&self) -> impl Iterator<Item = (usize, &str)> {
        self.errors
            .iter()
            .map(|(idx, error)| (*idx, error.as_str()))
    }
}

impl<T> From<Vec<T>> for VecWithError<T> {
    fn from(values: Vec<T>) -> Self {
        Self {
            values,
            errors: Vec::new(),
        }
    }
}

impl<'de, T: Deserialize<'de>> Deserialize<'de> for VecWithError<T> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct FaillibleVecVisitor<T>(std::marker::PhantomData<T>);
        impl<'de, T: Deserialize<'de>> Visitor<'de> for FaillibleVecVisitor<T> {
            type Value = VecWithError<T>;

            fn expecting(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                formatter.write_str("a list of values")
            }

            fn visit_seq<V>(self, mut seq: V) -> Result<Self::Value, V::Error>
            where
                V: SeqAccess<'de>,
            {
                let mut values = Vec::new();
                let mut errors = Vec::new();
                let mut index = 0;
                while let Some(raw_value) = seq.next_element::<&serde_json::value::RawValue>()? {
                    match serde_json::from_str::<T>(raw_value.get()) {
                        Ok(value) => {
                            values.push(value);
                        }
                        Err(error) => {
                            errors.push((index, error.to_string()));
                        }
                    }
                    index += 1;
                }
                Ok(VecWithError { values, errors })
            }
        }

        deserializer.deserialize_seq(FaillibleVecVisitor(std::marker::PhantomData))
    }
}

impl<T: Serialize> Serialize for VecWithError<T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        if !self.errors.is_empty() {
            Err(serde::ser::Error::custom("Vec contains invalid entries"))
        } else {
            let mut seq = serializer.serialize_seq(Some(self.values.len()))?;
            for e in &self.values {
                seq.serialize_element(e)?;
            }
            seq.end()
        }
    }
}
```

First, I would like to know if there is already a better way to do this? Maybe I missed an extension crate somewhere that provides this already? I haven't been able to find one.

If not, is there a way to make this work independently of the JSON format?
The two problems I see are:
* even if maybe `RawValue` would work for other data format, the call to `serde_json::from_str::<T>(raw_value.get())` to reparse the skipped entry is not generic.
* the error type returned by `serde_json::from_str` is not generic either which means I can't derive `Clone` or other traits because `serde_json::Error` does not implement those (I am not asking that serde_json::Error implements all the possible traits)

Again, I am not asking for this `VecWithError<T>` to be upstreamed in serde, but rather if you see a path to make this work more generically (maybe with some changes in serde)?

Also, It feels like this is somehow a similar problematic to the streaming deserialization.

Thank you in advance for your inputs!

**Comment by dtolnay** [comment]
The solution in your comment seems fine to me. If you need something that'll work in formats other than JSON, you could do `.next_element::<serde_value::Value>()` instead of `&RawValue`, and then `T::deserialize(value)` instead of `serde_json::from_str`.
