### ISSUE TITLE
`--features nightly-testing` failing

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#313]
```
error: unresolved import `core::nonzero::NonZero`. Could not find `nonzero` in `core` [E0432]
use core::nonzero::{NonZero, Zeroable};
                    ^~~~~~~
error: unresolved import `core::nonzero::Zeroable`. Could not find `nonzero` in `core` [E0432]
use core::nonzero::{NonZero, Zeroable};
                             ^~~~~~~~
error: unresolved import `core::num::Zero`. Could not find `num` in `core` [E0432]
use core::num::Zero;
    ^~~~~~~~~~~~~~~
error: unresolved import `core::num`. There is no `num` in `core` [E0432]
use core::num;
    ^~~~~~~~~
error: unresolved import `core::nonzero::NonZero`. Could not find `nonzero` in `core` [E0432]
use core::nonzero::{NonZero, Zeroable};
                    ^~~~~~~
error: unresolved import `core::nonzero::Zeroable`. Could not find `nonzero` in `core` [E0432]
use core::nonzero::{NonZero, Zeroable};
                             ^~~~~~~~
error: `Zeroable` is not a trait [E0404]
impl<T> Deserialize for NonZero<T> where T: Deserialize + PartialEq + Zeroable + Zero {
                                                                      ^~~~~~~~
error: `Zero` is not a trait [E0404]
impl<T> Deserialize for NonZero<T> where T: Deserialize + PartialEq + Zeroable + Zero {
                                                                                 ^~~~
error: failed to resolve. Use of undeclared type or module `num` [E0433]
     where A: Serialize + Clone + iter::Step + num::One,
                                               ^~~~~~~~
error: `Zeroable` is not a trait [E0404]
impl<T> Serialize for NonZero<T> where T: Serialize + Zeroable {
                                                      ^~~~~~~~
```

**Comment by dtolnay** [comment]
Caused by #302 (see its last Travis build: https://travis-ci.org/serde-rs/serde/builds/127547985).

**Comment by oli-obk** [comment]
was fixed by #314
