### ISSUE TITLE
Serde still causing errors even after 1.0.212

### ISSUE THREAD

**Issue by sffc** [serde-rs/serde#2846]
Serde 1.0.211 broke some call sites described in #2844 and later fixed in #2845

I believe it is still broken. The number of errors is reduced, but I am still seeing one:

```
...
  Downloaded serde_derive v1.0.212
...
error[E0425]: cannot find value `__e` in this scope
   --> components/datetime/src/provider/calendar/symbols.rs:336:36
    |
336 |                 deserialize_with = "icu_provider::serde_borrow_de_utils::array_of_cow"
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

CC @robertbastian
