### ISSUE TITLE
`serde::__private::de::Content::deserialize` not found in `Content<'_>` in `serde_derive` v1.0.224

### ISSUE THREAD

**Issue by ysaito1001** [serde-rs/serde#2982]
After upgrading `serde_derive` to v1.0.224, [our CI](https://github.com/smithy-lang/smithy-rs/actions/runs/17742524493/job/50420037613) has started failing to compile the `lambda_http` v0.8.3

```
error[E0599]: no variant or associated item named `deserialize` found for enum `serde_core::__private::content::Content` in the current scope
  --> /opt/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lambda_http-0.8.3/src/deserializer.rs:11:60
   |
11 |         let content = match serde::__private::de::Content::deserialize(deserializer) {
   |                                                            ^^^^^^^^^^^ variant or associated item not found in `Content<'_>`
```

Pinning `serde_derive` to exactly `=v1.0.219` helps work around the issue.

**Comment by oli-obk** [comment]
This is intentional. Please do not use API documented to disappear or break at any time
