### ISSUE TITLE
Version 1.0.104 does not compile with rustc-1.40.0 and feature derive

### ISSUE THREAD

**Issue by abique** [serde-rs/serde#1700]
Hi,

I followed the examples and here is the error:
```cargo build
   Compiling serde v1.0.104
error[E0432]: unresolved import `ser::Serializer`
 --> /home/abique/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/ser/impls.rs:3:45
  |
3 | use ser::{Error, Serialize, SerializeTuple, Serializer};
  |                                             ^^^^^^^^^^
  |                                             |
  |                                             no `Serializer` in `ser`
  |                                             help: a similar name exists in the module: `Serialize`

error[E0432]: unresolved import `ser::Serializer`
   --> /home/abique/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/lib.rs:248:26
    |
248 | pub use ser::{Serialize, Serializer};
    |                          ^^^^^^^^^^
    |                          |
    |                          no `Serializer` in `ser`
    |                          help: a similar name exists in the module: `Serialize`

error[E0432]: unresolved import `ser::Serializer`
 --> /home/abique/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/private/ser.rs:3:71
  |
3 | use ser::{self, Impossible, Serialize, SerializeMap, SerializeStruct, Serializer};
  |                                                                       ^^^^^^^^^^
  |                                                                       |
  |                                                                       no `Serializer` in `ser`
  |                                                                       help: a similar name exists in the module: `Serialize`

error[E0432]: unresolved import `ser::Serializer`
   --> /home/abique/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/private/ser.rs:369:32
    |
369 |     use ser::{self, Serialize, Serializer};
    |                                ^^^^^^^^^^
    |                                |
    |                                no `Serializer` in `ser`
    |                                help: a similar name exists in the module: `Serialize`

error[E0405]: cannot find trait `Serializer` in this scope
   --> /home/abique/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/ser/mod.rs:248:12
    |
215 | / pub trait Serialize {
216 | |     /// Serialize this value into the given Serde serializer.
217 | |     ///
218 | |     /// See the [Implementing `Serialize`] section of the manual for more
...   |
248 | |         S: Serializer;
    | |            ^^^^^^^^^^ help: a trait with a similar name exists: `Serialize`
249 | | }
    | |_- similarly named trait `Serialize` defined here

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0405, E0432.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `serde`.

To learn more, run the command again with --verbose.```

Looking at the error I believe that the issue on coming from Serde.
However I am a rust beginner and it could be on my side.

**Comment by abique** [comment]
I did kill my cargo cache, tried to build again and it worked...

**Comment by dtolnay** [comment]
I don't think there is going to be enough information here to debug this. If it builds successfully after clearing Cargo's cache then it's more likely a cargo bug or rustc bug than a serde bug. I am going to close this for now, but please let us know if you see something like this again and maybe have some way to reproduce it. Thanks!
