### PR TITLE
Correctly process flatten fields in enum variants

### LINKED ISSUE #1904: Deserialize failed to derive on enums with tuple variant and flatten struct variant
[Instead of thousand of words](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f1ea8c90736214e52d74c4ca0cab973b)

This code is failed to compile due to panic in serde derive:
```rust
#[derive(Deserialize)]
enum Failed {
    Tuple(f64, String),
    Flatten {
        #[serde(flatten)]
        nested: Nested,
    },
}
```
Output:
```bash
   Compiling playground v0.0.1 (/playground)
error: proc-macro derive panicked
  --> src/lib.rs:30:10
   |
30 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
   |
   = help: message: assertion failed: !cattrs.has_flatten()

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Each variant individually and `Serialize` derive works well, problem is only in combination of tuple variant and struct variant, when struct variant contains flattened field.

### LINKED ISSUE #2565: `#[serde(flatten)]` in struct variants errously propagated to all variants from one variant
In this enum `__Field` structs for both variants generated like the variant contains flattened field, but that is true only for the second field:
```rust
#[derive(Deserialize)]
enum Enum<T> {
    Simple {
        a: i32,
    },
    Flatten {
        #[serde(flatten)]
        flatten: T,
    },
}
```
This is happens because `has_flatten` field in `Container` struct becomes `true` for enums if any variant contains `#[serde(flatten)]`, but it makes little sense
https://github.com/serde-rs/serde/blob/05a5b7e3c6de502d45597cbc083f28bc1d4f4626/serde_derive/src/internals/attr.rs#L219

For enums `has_flatten` should be bound to the variant, not to the enum

### LINKED ISSUE #2792: `deny_unknown_fields` can break in 1.0.205
The following (reduction of a less artificial example)
```rust
#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
enum A {
    B {
        c: String,
    },
    D {
        #[serde(flatten)]
        e: E,
    },
}
#[derive(serde::Deserialize)]
struct E {}

```
compiles fine with 1.0.204 but produces the following error in 1.0.205:
```
error[E0004]: non-exhaustive patterns: `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field::__other(_)` not covered
 --> src/main.rs:1:10
  |
1 | #[derive(serde::Deserialize)]
  |          ^^^^^^^^^^^^^^^^^^ pattern `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field::__other(_)` not covered
  |
note: `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field<'_>` defined here
 --> src/main.rs:1:10
  |
1 | #[derive(serde::Deserialize)]
  |          ^^^^^^^^^^^^^^^^^^
  |          |
  |          not covered
  = note: the matched value is of type `<_::<impl Deserialize<'de> for A>::deserialize::__Visitor<'de> as Visitor<'de>>::visit_enum::__Field<'_>`
  = note: this error originates in the derive macro `serde::Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I have bisected the changes, and the issue appears in 32958dec3bf3886961166ec651194d6f0243a497

### PR DESCRIPTION
**Pull request by Mingun**
Store `has_flatten` mark in the `Variant` attributes and use it instead of `attr::Container::has_flatten()` in methods that can be called for variants.

Fixes #1904, fixes #2565, fixes #2792

### CODE REVIEW

**Comment by Mingun** [comment]
@dtolnay , when you could look at this? This bugs becomes annoying...

**Comment by Mingun** [comment]
@dtolnay, @oli-obk, can you give some feedback?

**Comment by Mingun** [comment]
@dtolnay, @oli-obk, can this bugfix be merged?

**Review by dtolnay — APPROVED** [review]
Thank you!
