### ISSUE TITLE
Does not compile on rustc 1.13.0-nightly (eac41469d 2016-08-30)

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#533]
```
error[E0308]: mismatched types
   --> src/attr.rs:137:64
    |
137 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> src/attr.rs:158:73
    |
158 |                         if let Ok((ser, de)) = get_where_predicates(cx, meta_items) {
    |                                                                         ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> src/attr.rs:229:64
    |
229 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> src/attr.rs:318:64
    |
318 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> src/attr.rs:377:73
    |
377 |                         if let Ok((ser, de)) = get_where_predicates(cx, meta_items) {
    |                                                                         ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> src/attr.rs:512:18
    |
512 |             Some(items)
    |                  ^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error: aborting due to 6 previous errors

error: Could not compile `serde_codegen_internals`.
```

**Comment by dtolnay** [comment]
Fixed in [0.8.5](https://github.com/serde-rs/serde/releases/tag/v0.8.5).
