### ISSUE TITLE
Deserialize lifetime issue + unknown variant attribute borrow (breaking change?)

### ISSUE THREAD

**Issue by withoutboats** [serde-rs/serde#927]
I have these types:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum RelData<'a> {
    Single(RelObject<'a>),
    Many(Vec<RelObject<'a>>),
}

#[derive(Deserialize)]
struct RelObject<'a> {
    #[serde(rename = "type")]
    #[allow(dead_code)]
    ty: &'a str,
    id: String,
}
```

This worked on 1.0.0, but when I upgraded to 1.0.4 it stopped working with these errors:

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'de` due to conflicting requirements
  --> mainsail/src/formats/jsonapi/receive/rels.rs:44:10
   |
44 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime 'de as defined on the body at 44:9...
  --> mainsail/src/formats/jsonapi/receive/rels.rs:44:10
   |
44 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
note: ...so that types are compatible (expected serde::Deserializer<'_>, found serde::Deserializer<'de>)
  --> mainsail/src/formats/jsonapi/receive/rels.rs:44:10
   |
44 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
note: but, the lifetime must be valid for the lifetime 'a as defined on the body at 44:9...
  --> mainsail/src/formats/jsonapi/receive/rels.rs:44:10
   |
44 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
note: ...so that types are compatible (expected serde::Deserialize<'_>, found serde::Deserialize<'_>)
  --> mainsail/src/formats/jsonapi/receive/rels.rs:44:10
   |
44 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^

error: aborting due to previous error
```

I looked for similar issues and found #920, however it looks like you don't support applying the `borrow` attribute to enum variants.

**Comment by oli-obk** [comment]
expanded:

```rust
use std::*;

enum RelData<'a> {
    Single(RelObject<'a>),
    Many(Vec<RelObject<'a>>),
}
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_RelData: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de, 'a> _serde::Deserialize<'de> for RelData<'a> {
        fn deserialize<__D>(__deserializer: __D) -> _serde::export::Result<Self, __D::Error>
            where __D: _serde::Deserializer<'de>
        {
            let __content =

                    match <_serde::private::de::Content as
                              _serde::Deserialize>::deserialize(__deserializer)
                        {
                        ::result::Result::Ok(val) => val,
                        ::result::Result::Err(err) => {
                            return ::result::Result::Err(::convert::From::from(err))
                        }
                    };
            if let _serde::export::Ok(__ok) =
                       _serde::export::Result::map(<RelObject<'a> as
                                                       _serde::Deserialize>::deserialize(_serde::private::de::ContentRefDeserializer::<__D::Error>::new(&__content)),
                                                   RelData::Single) {
                    return _serde::export::Ok(__ok);
                }
            if let _serde::export::Ok(__ok) =
                       _serde::export::Result::map(<Vec<RelObject<'a>> as
                                                       _serde::Deserialize>::deserialize(_serde::private::de::ContentRefDeserializer::<__D::Error>::new(&__content)),
                                                   RelData::Many) {
                    return _serde::export::Ok(__ok);
                }
            _serde::export::Err(_serde::de::Error::custom("data did not match any variant of \
                                                           untagged enum RelData"))
        }
    }
};
struct RelObject<'a> {
    ty: &'a str,
    id: String,
}
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_RelObject: () = {
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de: 'a, 'a> _serde::Deserialize<'de> for RelObject<'a> {
        fn deserialize<__D>(__deserializer: __D) -> _serde::export::Result<Self, __D::Error>
            where __D: _serde::Deserializer<'de>
        {
            #[allow(non_camel_case_types)]
            enum __Field {
                __field0,
                __field1,
                __ignore,
            }
            struct __FieldVisitor;
            impl<'de> _serde::de::Visitor<'de> for __FieldVisitor {
                type Value = __Field;
                fn expecting(&self,
                             formatter: &mut _serde::export::Formatter)
                             -> _serde::export::fmt::Result {
                    _serde::export::Formatter::write_str(formatter, "field identifier")
                }
                fn visit_str<__E>(self, __value: &str) -> _serde::export::Result<Self::Value, __E>
                    where __E: _serde::de::Error
                {
                    match __value {
                        "type" => _serde::export::Ok(__Field::__field0),
                        "id" => _serde::export::Ok(__Field::__field1),
                        _ => _serde::export::Ok(__Field::__ignore),
                    }
                }
                fn visit_bytes<__E>(self,
                                    __value: &[u8])
                                    -> _serde::export::Result<Self::Value, __E>
                    where __E: _serde::de::Error
                {
                    match __value {
                        b"type" => _serde::export::Ok(__Field::__field0),
                        b"id" => _serde::export::Ok(__Field::__field1),
                        _ => _serde::export::Ok(__Field::__ignore),
                    }
                }
            }
            impl<'de> _serde::Deserialize<'de> for __Field {
                #[inline]
                fn deserialize<__D>(__deserializer: __D) -> _serde::export::Result<Self, __D::Error>
                    where __D: _serde::Deserializer<'de>
                {
                    _serde::Deserializer::deserialize_identifier(__deserializer, __FieldVisitor)
                }
            }
            struct __Visitor<'de: 'a, 'a> {
                marker: _serde::export::PhantomData<RelObject<'a>>,
                lifetime: _serde::export::PhantomData<&'de ()>,
            }
            impl<'de: 'a, 'a> _serde::de::Visitor<'de> for __Visitor<'de, 'a> {
                type Value = RelObject<'a>;
                fn expecting(&self,
                             formatter: &mut _serde::export::Formatter)
                             -> _serde::export::fmt::Result {
                    _serde::export::Formatter::write_str(formatter, "struct RelObject")
                }
                #[inline]
                fn visit_seq<__A>(self,
                                  mut __seq: __A)
                                  -> _serde::export::Result<Self::Value, __A::Error>
                    where __A: _serde::de::SeqAccess<'de>
                {
                    let __field0 =
                        match match _serde::de::SeqAccess::next_element::<&'a str>(&mut __seq) {
                            ::result::Result::Ok(val) => val,
                            ::result::Result::Err(err) => {
                                return ::result::Result::Err(::convert::From::from(err))
                            }
                        } {
                            Some(__value) => __value,
                            None => {
                                return _serde::export::Err(_serde::de::Error::invalid_length(0usize,
                                                                                                 &"tuple of 2 elements"));
                            }
                        };
                    let __field1 =
                        match match _serde::de::SeqAccess::next_element::<String>(&mut __seq) {
                            ::result::Result::Ok(val) => val,
                            ::result::Result::Err(err) => {
                                return ::result::Result::Err(::convert::From::from(err))
                            }
                        } {
                            Some(__value) => __value,
                            None => {
                                return _serde::export::Err(_serde::de::Error::invalid_length(1usize,
                                                                                                 &"tuple of 2 elements"));
                            }
                        };
                    _serde::export::Ok(RelObject {
                        ty: __field0,
                        id: __field1,
                    })
                }
                #[inline]
                fn visit_map<__A>(self,
                                  mut __map: __A)
                                  -> _serde::export::Result<Self::Value, __A::Error>
                    where __A: _serde::de::MapAccess<'de>
                {
                    let mut __field0: _serde::export::Option<&'a str> = _serde::export::None;
                    let mut __field1: _serde::export::Option<String> = _serde::export::None;
                    while let _serde::export::Some(__key) =
                        match _serde::de::MapAccess::next_key::<__Field>(&mut __map) {
                            ::result::Result::Ok(val) => val,
                            ::result::Result::Err(err) => {
                                return ::result::Result::Err(::convert::From::from(err))
                            }
                        } {
                        match __key {
                            __Field::__field0 => {
                                if _serde::export::Option::is_some(&__field0) {
                                    return _serde::export::Err(<__A::Error
                                                                       as
                                                                       _serde::de::Error>::duplicate_field("type"));
                                }
                                __field0 =
                                        _serde::export::Some(match _serde::de::MapAccess::next_value::<&'a str>(&mut __map)
                                                                 {
                                                                 ::result::Result::Ok(val)
                                                                 => val,
                                                                 ::result::Result::Err(err)
                                                                 => {
                                                                     return ::result::Result::Err(::convert::From::from(err))
                                                                 }
                                                             });
                            }
                            __Field::__field1 => {
                                if _serde::export::Option::is_some(&__field1) {
                                    return _serde::export::Err(<__A::Error
                                                                       as
                                                                       _serde::de::Error>::duplicate_field("id"));
                                }
                                __field1 =
                                        _serde::export::Some(match _serde::de::MapAccess::next_value::<String>(&mut __map)
                                                                 {
                                                                 ::result::Result::Ok(val)
                                                                 => val,
                                                                 ::result::Result::Err(err)
                                                                 => {
                                                                     return ::result::Result::Err(::convert::From::from(err))
                                                                 }
                                                             });
                            }
                            _ => {
                                let _ =
                                        match _serde::de::MapAccess::next_value::<_serde::de::IgnoredAny>(&mut __map)
                                            {
                                            ::result::Result::Ok(val) => val,
                                            ::result::Result::Err(err) => {
                                                return ::result::Result::Err(::convert::From::from(err))
                                            }
                                        };
                            }
                        }
                    }
                    let __field0 = match __field0 {
                        _serde::export::Some(__field0) => __field0,
                        _serde::export::None => {
                            match _serde::private::de::missing_field("type") {
                                ::result::Result::Ok(val) => val,
                                ::result::Result::Err(err) => {
                                    return ::result::Result::Err(::convert::From::from(err))
                                }
                            }
                        }
                    };
                    let __field1 = match __field1 {
                        _serde::export::Some(__field1) => __field1,
                        _serde::export::None => {
                            match _serde::private::de::missing_field("id") {
                                ::result::Result::Ok(val) => val,
                                ::result::Result::Err(err) => {
                                    return ::result::Result::Err(::convert::From::from(err))
                                }
                            }
                        }
                    };
                    _serde::export::Ok(RelObject {
                        ty: __field0,
                        id: __field1,
                    })
                }
            }
            const FIELDS: &'static [&'static str] = &["type", "id"];
            _serde::Deserializer::deserialize_struct(__deserializer,
                                                         "RelObject", FIELDS,
                                                         __Visitor{marker:
                                                                       _serde::export::PhantomData::<RelObject<'a>>,
                                                                   lifetime:
                                                                       _serde::export::PhantomData,})
        }
    }
};
fn main() {}
```

expanded error:

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'de` due to conflicting requirements
  --> src/main.rs:17:27
   |
17 |                       match <_serde::private::de::Content as
   |  ___________________________^
18 | |                               _serde::Deserialize>::deserialize(__deserializer)
   | |_______________________________________________________________^
   |
note: first, the lifetime cannot outlive the lifetime 'de as defined on the body at 14:8...
  --> src/main.rs:14:9
   |
14 | /         {
15 | |             let __content =
16 | |
17 | |                     match <_serde::private::de::Content as
...  |
38 | |                                                            untagged enum RelData"))
39 | |         }
   | |_________^
note: ...so that types are compatible (expected _IMPL_DESERIALIZE_FOR_RelData::_serde::Deserializer<'_>, found _IMPL_DESERIALIZE_FOR_RelData::_serde::Deserializer<'de>)
  --> src/main.rs:17:27
   |
17 |                       match <_serde::private::de::Content as
   |  ___________________________^
18 | |                               _serde::Deserialize>::deserialize(__deserializer)
   | |_______________________________________________________________^
note: but, the lifetime must be valid for the lifetime 'a as defined on the body at 14:8...
  --> src/main.rs:14:9
   |
14 | /         {
15 | |             let __content =
16 | |
17 | |                     match <_serde::private::de::Content as
...  |
38 | |                                                            untagged enum RelData"))
39 | |         }
   | |_________^
note: ...so that types are compatible (expected _IMPL_DESERIALIZE_FOR_RelData::_serde::Deserialize<'_>, found _IMPL_DESERIALIZE_FOR_RelData::_serde::Deserialize<'_>)
  --> src/main.rs:32:52
   |
32 |                          _serde::export::Result::map(<Vec<RelObject<'a>> as
   |  ____________________________________________________^
33 | |                                                        _serde::Deserialize>::deserialize(_serde::private::de::ContentRefDeserializer::<__D::Error>::new(&__content))
,
   | |________________________________________________________________________________________^
```

**Comment by oli-obk** [comment]
we don't generate a `'de: 'a` bound for the `Deserialize` impl for `RelData`

This was fine before https://github.com/serde-rs/serde/pull/926 but is now relevant.

**Comment by oli-obk** [comment]
> however it looks like you don't support applying the borrow attribute to enum variants.

You don't need to borrow the variant, you need to borrow its fields:

```rust
enum RelData<'a> {
    Single(#[serde(borrow)]RelObject<'a>),
    Many(#[serde(borrow)]Vec<RelObject<'a>>),
}
```

**Comment by dtolnay** [comment]
Sorry about the break. I didn't expect such code to exist because it doesn't work. Using serde 1.0.0 and serde_derive 1.0.0 the following code fails to deserialize because borrowing was not supported inside of untagged enums. Your RelData was never deserialized successfully right? I guess aside from an empty array `[]`.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum RelData<'a> {
    Single(RelObject<'a>),
    Many(Vec<RelObject<'a>>),
}

#[derive(Deserialize, Debug)]
struct RelObject<'a> {
    #[serde(rename = "type")]
    #[allow(dead_code)]
    ty: &'a str,
    id: String,
}

fn main() {
    let s = r#" {"type":"without","id":"boats"} "#;
    let rel: RelData = serde_json::from_str(s).unwrap();
    println!("{:?}", rel);
}
```

To explain where the lifetime errors are coming from: because RelObject needs to borrow `&'a str`, it can only deserialize from data that outlives `'a`. Serde will implicitly borrow fields of type `&str` without you having to ask for it. But RelData does not ask to borrow anything so it expects to be able to deserialize from data that has any lifetime. This is a conflict because RelData can't deserialize from an arbitrary lifetime when one of the fields can only deserialize from a restricted lifetime.

The fix is to ask to borrow those fields. This way RelData knows it is only able to deserialize from data that outlives `'a`. Side note: I filed #929 to make this less ugly.

```rust
enum RelData<'a> {
    Single(#[serde(borrow)] RelObject<'a>),
    Many(#[serde(borrow)] Vec<RelObject<'a>>),
}
```

This was an unintentional breaking change but I think the best course of action is to leave it. It is good that it caught a bug in your program.

**Comment by withoutboats** [comment]
Sounds like it was a bug fix, then - that's good. Its true I never tried to deserialize this.

As a feature request, what do you think about allowing borrow to be applied to the variant, with equivalent semantics to applying it to all of the variant's members?
